### PR TITLE
Fix Custom Error Response // Add access to DI container

### PR DESCRIPTION
**Pull request by AReyes-cl**
Fix not working custom response on error
Add access to DI container

### CODE REVIEW

**Comment by dyorg** [comment]
Hi @AReyes-cl 

I just merged another pull request that fix custom response with better validation.

About inject DI container seens to be a bad practice. Do you can explain the reason to do it?

**Comment by AReyes-cl** [comment]
Hi @dyorg, I needed access to log and db functions into te DI container.

**Comment by dyorg** [comment]
Hi @AReyes-cl, I dont know exactly what you trying to do, but if you want access `$container` inside authenticator function, I think that you could pass `$container` with command `use`.

```php
$authenticator = function($request, TokenAuthentication $tokenAuth) use ($container) {

    ...

};

$app = new App();

$app->add(new TokenAuthentication([
    'path' => '/api',
    'authenticator' => $authenticator
]));
```

**Comment by AReyes-cl** [comment]
Basically the idea is to be able to access the database within authenticator function
I had already tried using the $app variable that way and it works fine but I did not find it a very elegant solution.
Thank you very much for your response.

**Comment by dyorg** [comment]
I believe that adopt `use` is the best way because keep the middleware flexible and with only the essential.

I will close this request. Thanks for collaborate!

**Pull request closed without merging**
